In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("cancer_b.csv")

In [ ]:
df.head()

,Id,Diagnosis,Radius (mean),Texture (mean),Perimeter (mean),Area (mean),Smoothness (mean),Compactness (mean),Concavity (mean),Concave points (mean),...,Radius (worst),Texture (worst),Perimeter (worst),Area (worst),Smoothness (worst),Compactness (worst),Concavity (worst),Concave points (worst),Symmetry (worst),Fractal dimension (worst)
0,8510426,B,13.540,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.047810,...,15.110,19.26,99.70,711.2,0.14400,0.17730,0.23900,0.12880,0.2977,0.07259
1,8510653,A,13.080,15.71,85.63,520.0,0.10750,0.12700,0.04568,0.031100,...,14.500,20.49,96.09,630.5,0.13120,0.27760,0.18900,0.07283,0.3184,0.08183
2,8510824,B,9.504,12.44,60.34,273.9,0.10240,0.06492,0.02956,0.020760,...,10.230,15.66,65.13,314.9,0.13240,0.11480,0.08867,0.06227,0.2450,0.07773
3,854941,B,13.030,18.42,82.61,523.8,0.08983,0.03766,0.02562,0.029230,...,13.300,22.81,84.46,545.9,0.09701,0.04619,0.04833,0.05013,0.1987,0.06169
4,85713702,B,8.196,16.84,51.71,201.9,0.08600,0.05943,0.01588,0.005917,...,8.964,21.96,57.26,242.2,0.12970,0.13570,0.06880,0.02564,0.3105,0.07409

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         357 non-null    int64
 1   Diagnosis                  357 non-null    str
 2   Radius (mean)              357 non-null    float64
 3   Texture (mean)             357 non-null    float64
 4   Perimeter (mean)           357 non-null    float64
 5   Area (mean)                357 non-null    float64
 6   Smoothness (mean)          357 non-null    float64
 7   Compactness (mean)         357 non-null    float64
 8   Concavity (mean)           357 non-null    float64
 9   Concave points (mean)      357 non-null    float64
 10  Symmetry (mean)            357 non-null    float64
 11  Fractal dimension (mean)   357 non-null    float64
 12  Radius (se)                357 non-null    float64
 13  Texture (se)               357 non-null    float64
 14  Perimeter (se)             357 non-null    float64
 15  Area (se)                  357 non-null    float64
 16  Smoothness (se)            357 non-null    float64
 17  Compactness (se)           357 non-null    float64
 18  Concavity (se)             357 non-null    float64
 19  Concave points (se)        357 non-null    float64
 20  Symmetry (se)              357 non-null    float64
 21  Fractal dimension (se)     357 non-null    float64
 22  Radius (worst)             357 non-null    float64
 23  Texture (worst)            357 non-null    float64
 24  Perimeter (worst)          357 non-null    float64
 25  Area (worst)               357 non-null    float64
 26  Smoothness (worst)         357 non-null    float64
 27  Compactness (worst)        357 non-null    float64
 28  Concavity (worst)          357 non-null    float64
 29  Concave points (worst)     357 non-null    float64
 30  Symmetry (worst)           357 non-null    float64
 31  Fractal dimension (worst)  357 non-null    float64
dtypes: float64(30), int64(1), str(1)
memory usage: 89.4 KB

In [ ]:
df.describe()

,Id,Radius (mean),Texture (mean),Perimeter (mean),Area (mean),Smoothness (mean),Compactness (mean),Concavity (mean),Concave points (mean),Symmetry (mean),...,Radius (worst),Texture (worst),Perimeter (worst),Area (worst),Smoothness (worst),Compactness (worst),Concavity (worst),Concave points (worst),Symmetry (worst),Fractal dimension (worst)
count,3.570000e+02,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,...,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000
mean,2.654382e+07,12.146524,17.914762,78.075406,462.790196,0.092478,0.080085,0.046058,0.025717,0.174186,...,13.379801,23.515070,87.005938,558.899440,0.124959,0.182673,0.166238,0.074444,0.270246,0.079442
std,1.167397e+08,1.780512,3.995125,11.807438,134.287118,0.013446,0.033750,0.043442,0.015909,0.024807,...,1.981368,5.493955,13.527091,163.601424,0.020013,0.092180,0.140368,0.035797,0.041745,0.013804
min,8.913000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156600,0.055210
25%,8.746620e+05,11.080000,15.150000,70.870000,378.200000,0.083060,0.055620,0.020310,0.015020,0.158000,...,12.080000,19.580000,78.270000,447.100000,0.110400,0.112000,0.077080,0.051040,0.240600,0.070090
50%,9.089160e+05,12.200000,17.390000,78.180000,458.400000,0.090760,0.075290,0.037090,0.023440,0.171400,...,13.350000,22.820000,86.920000,547.400000,0.125400,0.169800,0.141200,0.074310,0.268700,0.077120
75%,8.812816e+06,13.370000,19.760000,86.100000,551.100000,0.100700,0.097550,0.059990,0.032510,0.189000,...,14.800000,26.510000,96.590000,670.000000,0.137600,0.230200,0.221600,0.097490,0.298300,0.085410
max,9.113205e+08,17.850000,33.810000,114.600000,992.100000,0.163400,0.223900,0.410800,0.085340,0.274300,...,19.820000,41.780000,127.100000,1210.000000,0.200600,0.584900,1.252000,0.175000,0.422800,0.148600

In [ ]:
df.count()

Id                           357
Diagnosis                    357
Radius (mean)                357
Texture (mean)               357
Perimeter (mean)             357
Area (mean)                  357
Smoothness (mean)            357
Compactness (mean)           357
Concavity (mean)             357
Concave points (mean)        357
Symmetry (mean)              357
Fractal dimension (mean)     357
Radius (se)                  357
Texture (se)                 357
Perimeter (se)               357
Area (se)                    357
Smoothness (se)              357
Compactness (se)             357
Concavity (se)               357
Concave points (se)          357
Symmetry (se)                357
Fractal dimension (se)       357
Radius (worst)               357
Texture (worst)              357
Perimeter (worst)            357
Area (worst)                 357
Smoothness (worst)           357
Compactness (worst)          357
Concavity (worst)            357
Concave points (worst)       357
Symmetry (worst)             357
Fractal dimension (worst)    357
dtype: int64

In [ ]:
df.isnull()

,Id,Diagnosis,Radius (mean),Texture (mean),Perimeter (mean),Area (mean),Smoothness (mean),Compactness (mean),Concavity (mean),Concave points (mean),...,Radius (worst),Texture (worst),Perimeter (worst),Area (worst),Smoothness (worst),Compactness (worst),Concavity (worst),Concave points (worst),Symmetry (worst),Fractal dimension (worst)
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
353,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
354,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
355,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
356,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

Id                           0
Diagnosis                    0
Radius (mean)                0
Texture (mean)               0
Perimeter (mean)             0
Area (mean)                  0
Smoothness (mean)            0
Compactness (mean)           0
Concavity (mean)             0
Concave points (mean)        0
Symmetry (mean)              0
Fractal dimension (mean)     0
Radius (se)                  0
Texture (se)                 0
Perimeter (se)               0
Area (se)                    0
Smoothness (se)              0
Compactness (se)             0
Concavity (se)               0
Concave points (se)          0
Symmetry (se)                0
Fractal dimension (se)       0
Radius (worst)               0
Texture (worst)              0
Perimeter (worst)            0
Area (worst)                 0
Smoothness (worst)           0
Compactness (worst)          0
Concavity (worst)            0
Concave points (worst)       0
Symmetry (worst)             0
Fractal dimension (worst)    0
dtype: int64

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
352    False
353    False
354    False
355    False
356    False
Length: 357, dtype: bool

In [ ]:
df.columns

Index(['Id', 'Diagnosis', 'Radius (mean)', 'Texture (mean)',
       'Perimeter (mean)', 'Area (mean)', 'Smoothness (mean)',
       'Compactness (mean)', 'Concavity (mean)', 'Concave points (mean)',
       'Symmetry (mean)', 'Fractal dimension (mean)', 'Radius (se)',
       'Texture (se)', 'Perimeter (se)', 'Area (se)', 'Smoothness (se)',
       'Compactness (se)', 'Concavity (se)', 'Concave points (se)',
       'Symmetry (se)', 'Fractal dimension (se)', 'Radius (worst)',
       'Texture (worst)', 'Perimeter (worst)', 'Area (worst)',
       'Smoothness (worst)', 'Compactness (worst)', 'Concavity (worst)',
       'Concave points (worst)', 'Symmetry (worst)',
       'Fractal dimension (worst)'],
      dtype='str')

In [ ]:
# df.drop(columns = 'Id')

In [ ]:
df_clean = df[['Id','Diagnosis','Radius (mean)','Area (mean)', 'Smoothness (mean)']]

In [ ]:
df_clean

           Id Diagnosis  Radius (mean)  Area (mean)  Smoothness (mean)
0     8510426         B         13.540        566.3            0.09779
1     8510653         A         13.080        520.0            0.10750
2     8510824         B          9.504        273.9            0.10240
3      854941         B         13.030        523.8            0.08983
4    85713702         B          8.196        201.9            0.08600
..        ...       ...            ...          ...                ...
352    925277         B         14.590        657.1            0.08473
353    925291         B         11.510        403.5            0.09261
354    925292         B         14.050        600.4            0.09929
355    925311         B         11.200        386.0            0.07449
356     92751         B          7.760        181.0            0.05263

[357 rows x 5 columns]

In [ ]:
df_clean.describe()

                 Id  Radius (mean)  Area (mean)  Smoothness (mean)
count  3.570000e+02     357.000000   357.000000         357.000000
mean   2.654382e+07      12.146524   462.790196           0.092478
std    1.167397e+08       1.780512   134.287118           0.013446
min    8.913000e+03       6.981000   143.500000           0.052630
25%    8.746620e+05      11.080000   378.200000           0.083060
50%    9.089160e+05      12.200000   458.400000           0.090760
75%    8.812816e+06      13.370000   551.100000           0.100700
max    9.113205e+08      17.850000   992.100000           0.163400

In [ ]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 357 non-null    int64
 1   Diagnosis          357 non-null    str
 2   Radius (mean)      357 non-null    float64
 3   Area (mean)        357 non-null    float64
 4   Smoothness (mean)  357 non-null    float64
dtypes: float64(3), int64(1), str(1)
memory usage: 14.1 KB

In [ ]:
df_clean['Diagnosis'].unique()

<StringArray>
['B', 'A']
Length: 2, dtype: str

In [ ]:
len(df_clean['Id'].unique())

357

In [ ]:
df_clean['Diagnosis'].value_counts()

Diagnosis
B    351
A      6
Name: count, dtype: int64

#### Acceptance value

1. LowerBond = Q1 - 1.5*(IQR)
2. UpperBond = Q3 + 1.5*(IQR)

    IQR = Q3 - Q1

In [ ]:
Q1 = df['Area (mean)'].quantile(0.25)
Q3 = df['Area (mean)'].quantile(0.75)

In [ ]:
IQR = Q3 - Q1

In [ ]:
LowerBond = Q1 - 1.5*(IQR)
UpperBond = Q3 + 1.5*(IQR)

In [ ]:
print("LowerBond: ",LowerBond)
print("UpperBond: ",UpperBond)

LowerBond:  118.84999999999997
UpperBond:  810.45

In [ ]:
outliersarea = df[(df['Area (mean)'] < LowerBond) | (df['Area (mean)'] > UpperBond)]
outliersarea

,Id,Diagnosis,Radius (mean),Texture (mean),Perimeter (mean),Area (mean),Smoothness (mean),Compactness (mean),Concavity (mean),Concave points (mean),...,Radius (worst),Texture (worst),Perimeter (worst),Area (worst),Smoothness (worst),Compactness (worst),Concavity (worst),Concave points (worst),Symmetry (worst),Fractal dimension (worst)
73,8711216,B,16.84,19.46,108.4,880.2,0.07445,0.07223,0.05150,0.02771,...,18.22,28.07,120.3,1032.0,0.08774,0.17100,0.1882,0.08436,0.2527,0.05972
202,9010872,B,16.50,18.29,106.6,838.1,0.09686,0.08468,0.05862,0.04835,...,18.13,25.45,117.2,1009.0,0.13380,0.16790,0.1663,0.09123,0.2394,0.06469
299,91376702,B,17.85,13.23,114.6,992.1,0.07838,0.06217,0.04445,0.04178,...,19.82,18.42,127.1,1210.0,0.09862,0.09976,0.1048,0.08341,0.1783,0.05871
311,915452,B,16.30,15.70,104.7,819.8,0.09427,0.06712,0.05526,0.04563,...,17.32,17.76,109.8,928.2,0.13540,0.13610,0.1947,0.13570,0.2300,0.07230