# Decision Tree Regression

In [11]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error,accuracy_score,confusion_matrix,classification_report

In [12]:
df = pd.read_csv('Chocolate Sales (2).csv')

In [13]:
df

          Sales Person    Country  ...      Amount Boxes Shipped
0       Jehu Rudeforth         UK  ...   $5,320.00           180
1          Van Tuxwell      India  ...   $7,896.00            94
2         Gigi Bohling      India  ...   $4,501.00            91
3         Jan Morforth  Australia  ...  $12,726.00           342
4       Jehu Rudeforth         UK  ...  $13,685.00           184
...                ...        ...  ...         ...           ...
3277  Karlen McCaffrey  Australia  ...   $5,303.58           354
3278    Jehu Rudeforth        USA  ...   $7,339.32           121
3279      Ches Bonnell     Canada  ...     $616.09           238
3280    Dotty Strutley      India  ...   $2,504.62           397
3281  Karlen McCaffrey      India  ...   $5,915.87           355

[3282 rows x 6 columns]

In [14]:
df.columns

Index(['Sales Person', 'Country', 'Product', 'Date', 'Amount',
       'Boxes Shipped'],
      dtype='str')

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   str
 4   Amount         3282 non-null   str
 5   Boxes Shipped  3282 non-null   int64
dtypes: int64(1), str(5)
memory usage: 154.0 KB

In [16]:
df.describe()

       Boxes Shipped
count    3282.000000
mean      164.666971
std       124.024736
min         1.000000
25%        71.000000
50%       137.000000
75%       232.000000
max       778.000000

In [17]:
df.isnull().sum()

Sales Person     0
Country          0
Product          0
Date             0
Amount           0
Boxes Shipped    0
dtype: int64